apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJVbVZrVFdVeGIyNDZaMmh3WDFZeVpHbzFka3h0T1VwcWJIQjFiMFpoV1hnMVJVcFVVWGxhTmxOVVJqSm5TV1pZVVE9PSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson
